// Reproducible build of the Vault editor bundle. Build-time only.
//   npm ci && node build.mjs          write kit/app/static/vault-editor.bundle.js (+ licences)
//   npm ci && node build.mjs --check  exit 1 if the committed files differ from a fresh build
import {build} from 'esbuild';
import {createHash} from 'node:crypto';
import {readFileSync, writeFileSync, existsSync, mkdirSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '../../kit/app/static');
const lock = JSON.parse(readFileSync(join(here, 'package-lock.json'), 'utf8'));
const lockHash = createHash('sha256').update(readFileSync(join(here, 'package-lock.json'))).digest('hex');
const shipped = Object.entries(lock.packages)
  .filter(([path, p]) => path.startsWith('node_modules/') && !p.dev && !p.optional)
  .map(([path, p]) => [path.slice('node_modules/'.length), p.version, p.license]).sort();

const header = `/* Tamanitomo Vault editor bundle (CodeMirror 6). Generated by tools/editor/build.mjs; do not edit.
 * package-lock sha256 ${lockHash}
${shipped.map(([n, v, l]) => ` * ${n}@${v} (${l})`).join('\n')}
 * Licences: vault-editor.LICENSES.txt */\n`;

const result = await build({
  entryPoints: [join(here, 'entry.js')], bundle: true, format: 'iife', minify: true,
  target: ['es2020'], legalComments: 'none', write: false, charset: 'utf8',
  absWorkingDir: here, logLevel: 'warning',
});
const bundle = header + result.outputFiles[0].text;

const licences = shipped.map(([name, version]) => {
  const dir = join(here, 'node_modules', name);
  const file = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license'].map(f => join(dir, f)).find(existsSync);
  if (!file) throw new Error(`No licence file for ${name}`);
  return `==== ${name}@${version} ====\n\n${readFileSync(file, 'utf8').trim()}\n`;
}).join('\n');

const files = {'vault-editor.bundle.js': bundle, 'vault-editor.LICENSES.txt': licences};
if (process.argv.includes('--check')) {
  const drift = Object.entries(files).filter(([name, text]) =>
    !existsSync(join(out, name)) || readFileSync(join(out, name), 'utf8') !== text).map(([n]) => n);
  if (drift.length) { console.error('Editor bundle drift: ' + drift.join(', ') + ' (run: npm ci && node build.mjs)'); process.exit(1); }
  console.log('Editor bundle matches a fresh build (lock ' + lockHash.slice(0, 12) + ')');
} else {
  mkdirSync(out, {recursive: true});
  for (const [name, text] of Object.entries(files)) writeFileSync(join(out, name), text);
  console.log(`Wrote ${Object.keys(files).join(', ')}: ${bundle.length} bytes, lock ${lockHash.slice(0, 12)}`);
}
