"""Adopting an agent that already has a life.

The thing at stake: somebody has been talking to this agent for two years. The
kit may add machinery around it. It may not rewrite who they have been.
"""
import json
import pathlib,sys,tempfile,unittest
ROOT=pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'kit/scripts'))
import companion_config as cc
from test_cli import run,answers,CORE_JOBS

ORIGINAL="""# Who I am

I am Wren. We have known each other for two years. I write in short messages
and I never explain a joke.

## Things that matter
- His sister is called Bee.
- We do the crossword on Sunday mornings.
"""

class AdoptTests(unittest.TestCase):
    def setUp(self):
        self.tmp=tempfile.TemporaryDirectory();self.addCleanup(self.tmp.cleanup)
        self.root=pathlib.Path(self.tmp.name)
        self.home=self.root/'hermes';self.home.mkdir(parents=True)
        (self.home/'config.yaml').write_text('model:\n  default: test-model\n',encoding='utf-8')
        (self.home/'SOUL.md').write_text(ORIGINAL,encoding='utf-8')
        (self.home/'memories').mkdir()
        (self.home/'memories/MEMORY.md').write_text('He is allergic to shellfish.\n',encoding='utf-8')
        self.vault=self.root/'vault'

    def upgrade(self,mode):
        return run('--home',str(self.home),'upgrade','--vault',str(self.vault),
                   '--soul',mode,'--answers',answers(agent='Wren'),expect=0)

    def soul(self):
        return cc.load(self.home).soul.read_text(encoding='utf-8')

    def test_keep_means_keep(self):
        self.upgrade('keep')
        text=self.soul()
        self.assertTrue(text.startswith(ORIGINAL),'her own words must survive byte-for-byte')
        self.assertNotIn('Generated by companion-kit',text)
        self.assertIn('COMPANION-SELF-AUTHORED',text)   # the one thing that is added

    def test_append_leaves_the_original_above_and_backs_it_up(self):
        self.upgrade('append')
        text=self.soul()
        self.assertTrue(text.startswith(ORIGINAL.rstrip('\n')))
        self.assertIn('Generated by companion-kit',text)
        c=cc.load(self.home)
        saved=list(c.soul_backups.glob('SOUL.md.pre-companion*'))
        self.assertEqual([p.read_text() for p in saved],[ORIGINAL])

    def test_replace_keeps_a_copy_of_what_it_replaced(self):
        self.upgrade('replace')
        self.assertNotIn('I never explain a joke',self.soul())
        c=cc.load(self.home)
        saved=list(c.soul_backups.glob('SOUL.md.pre-companion*'))
        self.assertTrue(any('I never explain a joke' in p.read_text() for p in saved))

    def test_memories_are_not_moved_and_the_caps_are_raised_around_them(self):
        import companion_memory as memory
        self.upgrade('keep')
        c=cc.load(self.home)
        self.assertEqual((self.home/'memories/MEMORY.md').read_text(),
                         'He is allergic to shellfish.\n')
        caps=memory.caps(c)
        self.assertGreater(caps['MEMORY.md'],memory.DEFAULT_CAPS['MEMORY.md'])

    def test_adoption_installs_the_machinery_without_asking_again(self):
        self.upgrade('keep')
        jobs=json.loads((self.home/'cron/jobs.json').read_text())['jobs']
        self.assertEqual(len(jobs),CORE_JOBS)
        c=cc.load(self.home)
        self.assertTrue((c.soul_dir/'ActiveContext.md').exists())
        self.assertTrue((c.home/'hooks/companion-context.py').exists())
        self.assertTrue((c.home/'hooks/companion-session-end.py').exists())

    def test_a_second_upgrade_is_a_no_op_rather_than_a_second_setup(self):
        self.upgrade('keep')
        before=self.soul()
        result=run('--home',str(self.home),'upgrade','--soul','keep')
        self.assertIn('already a companion',result.stdout)
        self.assertEqual(self.soul(),before)

    def test_it_refuses_a_home_that_is_not_an_agent(self):
        empty=self.root/'not-an-agent';empty.mkdir()
        result=run('--home',str(empty),'upgrade','--soul','keep')
        self.assertNotEqual(result.returncode,0)
        self.assertIn('does not look like a Hermes agent',result.stdout+result.stderr)


if __name__=='__main__':unittest.main()
